# ===================================
#  Form Behavior Config
# ===================================

form: ~/plugins/zmark/seo/models/seo/fields.yaml
modelClass: Zmark\Seo\Models\Seo
defaultRedirect: zmark/seo/seo

create:
  title: backend::lang.form.create_title
  redirect: zmark/seo/seo/update/:id
  redirectClose: zmark/seo/seo/
  flashSave: backend::lang.form.create_success

update:
  title: backend::lang.form.update_title
  redirectClose: zmark/seo/seo
  flashSave: backend::lang.form.update_success
